name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cloud_firestore: ^5.4.5
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.2
  google_sign_in: ^6.2.2
  firebase_core: ^3.7.0
  firebase_storage: ^12.3.5
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  get: ^4.6.6
  http: ^1.2.2
  image: ^4.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences: ^2.3.4
  velocity_x: ^4.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lib/Services/category_model.json
    - assets/images/
    - assets/icons/
    - assets/

  fonts:
    - family: sans_regular
      fonts:
        - asset: assets/fonts/sans_regular.ttf

    - family: sans_semibold
      fonts:
        - asset: assets/fonts/sans_semibold.ttf

    - family: sans_bold
      fonts:
        - asset: assets/fonts/sans_bold.ttf
